version: "3.9"

services:
  web-app:
    build: .
    restart: "always"
    container_name: "web-app"
    ports:
      - "3000:3000"
    volumes:
      - ./:/web-app
      - /web-app/node_modules
      - /web-app/.next